### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by arianacofone** [arianacofone/space_invaders#1]
Context
In trying to figure out the navigation frame work for space invaders, it took me down the path of the canvas element and I'm am just frozen has to how to integrate/work with that element, especially with how it interacts with the rest of the game.

Give information about what you have done to solve the problem. Including but not limited to:

I've watched every video that discusses/uses canvas and when I do just the simple act of trying to make a rectangle on the board, I am never successful. MDN was helpful in understanding how canvas works, but when I implemented it, no dice. At this point, I just feel like I've bit off more than I can chew.

What would you like help with specifically?
Getting a rectangle on the canvas and making it move right/left.

**Comment by arianacofone** [comment]
Sorry about not tagging you!

**Comment by amadden80** [comment]
Let's work on this together now.  All good!

**Comment by arianacofone** [comment]
cool! coming over!

**Comment by amadden80** [comment]
Let's review this before the end of day!

``` js
class Andrew {
  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.el = new Image();
    this.el.src = 'http://andrewmadden.com/face.png';
  }
  setArrowHandler() {
    document.body.addEventListener('keypress', (e) => {
      if (e.keyCode == 44) {
        this.x -= 5;
      } else if (e.keyCode == 46) {
        this.x += 5;
      }
    });
  }
}



// class Lazer {
//   constructor(x, y) {
//     this.x = x;
//     this.y = y;
//     this.velocity;
//     this.el = new Image();
//     this.el.src = 'http://andrewmadden.com/face.png';
//   }
//   step() {
//     this.y += this.velocity;
//   }
// }


const andrew = new Andrew(0, 200);
andrew.setArrowHandler();


function draw() {
  var canvasContext = document.getElementById('my-canvas').getContext('2d');
  canvasContext.clearRect(0,0,300,300);
  canvasContext.globalCompositeOperation = 'destination-over';
  canvasContext.drawImage(andrew.el, andrew.x, andrew.y, 100, 100);
  window.requestAnimationFrame(draw);
}

draw();

```
